### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by katk0smos** [orionsoft/react-meteor-data#8]
I'm getting an error relating to this while attempting to setup Flow Router, as React Router 4 doesn't have the ease of use I'm looking for. Here's the error:
```
/home/thewaffledimension/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Class extends value undefined is not a constructor or null
    at ReactMeteorData.jsx (packages/react-meteor-data/ReactMeteorData.jsx:164:40)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at createContainer.jsx (packages/react-meteor-data/createContainer.jsx:1:210)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:1:14)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /home/thewaffledimension/projects/web/react-app/.meteor/local/build/programs/server/packages/react-meteor-data.js:332:15
Exited with code: 1
```

**Comment by maxnowack** [comment]
I'm not sure if this package is still maintained. But as an alternative, you can try [react-tracker-connect](https://github.com/maxnowack/react-tracker-connect). It's works just like this package, but with lesser unnecessary reruns of reactive functions.
